UPDATE public.operacao SET nome = 'Iniciar Sessão do Operador após Fechamento Diário',
imprimir = true, asciioperacao = 0, modificado = true, desativado = null WHERE id = 24;

UPDATE public.operacao SET desativado = current_date WHERE id IN(33, 65);

ALTER TABLE IF EXISTS public.operacao
  ADD COLUMN IF NOT EXISTS nome_reduzido VARCHAR(50);
  
UPDATE public.operacao SET nome_reduzido = 'Abrir Caixa'  WHERE id = 1;
UPDATE public.operacao SET nome_reduzido = 'Fechar Caixa' WHERE id = 2;
UPDATE public.operacao SET nome_reduzido = 'Venda Diária' WHERE id = 3;
UPDATE public.operacao SET nome_reduzido = 'Fechamento Diário' WHERE id = 4;
UPDATE public.operacao SET nome_reduzido = 'Iniciar Sessão'    WHERE id = 5;
UPDATE public.operacao SET nome_reduzido = 'Fechar Sessão'     WHERE id = 6;
UPDATE public.operacao SET nome_reduzido = 'Abrir Cupom'       WHERE id = 7;
UPDATE public.operacao SET nome_reduzido = 'Fechar Cupom'      WHERE id = 8;
UPDATE public.operacao SET nome_reduzido = 'Cancelar Item'     WHERE id = 9;
UPDATE public.operacao SET nome_reduzido = 'Totalizar Cupom'   WHERE id = 10;
UPDATE public.operacao SET nome_reduzido = 'Cancelar Último Cupom' WHERE id = 11;
UPDATE public.operacao SET nome_reduzido = 'Suprimento'        WHERE id = 12;
UPDATE public.operacao SET nome_reduzido = 'Cancelar Item'     WHERE id = 13;
UPDATE public.operacao SET nome_reduzido = 'Cartão de Crédito' WHERE id = 14;
UPDATE public.operacao SET nome_reduzido = 'Cartão de Débito'  WHERE id = 15;
UPDATE public.operacao SET nome_reduzido = 'Cheque'            WHERE id = 16;
UPDATE public.operacao SET nome_reduzido = 'Aplicar Desconto'  WHERE id = 17;
UPDATE public.operacao SET nome_reduzido = 'Transações TEF'    WHERE id = 18;
UPDATE public.operacao SET nome_reduzido = 'Pagamento TEF'     WHERE id = 19;
UPDATE public.operacao SET nome_reduzido = 'Liberar Pagamento' WHERE id = 20;
UPDATE public.operacao SET nome_reduzido = 'Recarga de Celular' WHERE id = 21;
UPDATE public.operacao SET nome_reduzido = 'Adicionar Itens' WHERE id = 22;
UPDATE public.operacao SET nome_reduzido = 'Comprovante de Entrega'  WHERE id = 23;
UPDATE public.operacao SET nome_reduzido = 'Iniciar Sessão Pós Fechamento' WHERE id = 24;
UPDATE public.operacao SET nome_reduzido = 'Relatório de Sessão' WHERE id = 25;
UPDATE public.operacao SET nome_reduzido = 'Item via Consulta'   WHERE id = 26;
UPDATE public.operacao SET nome_reduzido = 'Consultar Preço'     WHERE id = 30;
UPDATE public.operacao SET nome_reduzido = 'Menu Fiscal'         WHERE id = 31;
UPDATE public.operacao SET nome_reduzido = 'Formas de Pagamento' WHERE id = 32;
UPDATE public.operacao SET nome_reduzido = 'Cheque Pré-Datado'   WHERE id = 35;
UPDATE public.operacao SET nome_reduzido = 'Convênio/Crediário'  WHERE id = 36;
UPDATE public.operacao SET nome_reduzido = 'Abrir Gaveta'        WHERE id = 37;
UPDATE public.operacao SET nome_reduzido = 'Envio Movimento Atual'    WHERE id = 38;
UPDATE public.operacao SET nome_reduzido = 'Abrir Cupom Identificado' WHERE id = 39;
UPDATE public.operacao SET nome_reduzido = 'Última Atualização'       WHERE id = 40;
UPDATE public.operacao SET nome_reduzido = 'Correspondente Bancário'  WHERE id = 41;
UPDATE public.operacao SET nome_reduzido = 'Cancelar TEF'      WHERE id = 50;
UPDATE public.operacao SET nome_reduzido = 'Desbloquear Caixa' WHERE id = 52;
UPDATE public.operacao SET nome_reduzido = 'Menu Caixa'        WHERE id = 53;
UPDATE public.operacao SET nome_reduzido = 'Menu Consulta'     WHERE id = 54;
UPDATE public.operacao SET nome_reduzido = 'Menu Cancelamento' WHERE id = 55;
UPDATE public.operacao SET nome_reduzido = 'Menu Pagamento'    WHERE id = 56;
UPDATE public.operacao SET nome_reduzido = 'Menu Suporte'      WHERE id = 57;
UPDATE public.operacao SET nome_reduzido = 'Cartão Manual'     WHERE id = 67;
UPDATE public.operacao SET nome_reduzido = 'Pagamento Dinheiro' WHERE id = 68;
UPDATE public.operacao SET nome_reduzido = 'Pagamento Ticket'   WHERE id = 69;
UPDATE public.operacao SET nome_reduzido = 'Cancelar Item'      WHERE id = 71;
UPDATE public.operacao SET nome_reduzido = 'Voltar Atualização' WHERE id = 72;
UPDATE public.operacao SET nome_reduzido = 'Multiplicador'      WHERE id = 73;
UPDATE public.operacao SET nome_reduzido = 'Funções Adicionais' WHERE id = 79;
UPDATE public.operacao SET nome_reduzido = 'Envio Movimento por Data' WHERE id = 89;
UPDATE public.operacao SET nome_reduzido = 'Desconto Percentual'   WHERE id = 91;
UPDATE public.operacao SET nome_reduzido = 'Sangria' WHERE id = 100;
UPDATE public.operacao SET nome_reduzido = 'Consultar Preço'   WHERE id = 101;
UPDATE public.operacao SET nome_reduzido = 'Consultar Preço'   WHERE id = 102;
UPDATE public.operacao SET nome_reduzido = 'Consultar Cliente' WHERE id = 103;
UPDATE public.operacao SET nome_reduzido = 'Acertar Data'      WHERE id = 104;
UPDATE public.operacao SET nome_reduzido = 'Limite do Cliente'       WHERE id = 106;
UPDATE public.operacao SET nome_reduzido = 'Aplicar Desconto' WHERE id = 107;
UPDATE public.operacao SET nome_reduzido = 'Pré-venda'               WHERE id = 108;
UPDATE public.operacao SET nome_reduzido = 'Pagamento Cheque'        WHERE id = 109;
UPDATE public.operacao SET nome_reduzido = 'Alterar Forma de Emissão' WHERE id = 111;
UPDATE public.operacao SET nome_reduzido = 'Pagar Estacionamento'     WHERE id = 112;
UPDATE public.operacao SET nome_reduzido = 'Sobre'                   WHERE id = 116;
UPDATE public.operacao SET nome_reduzido = 'Divergência de Peso'     WHERE id = 118;
UPDATE public.operacao SET nome_reduzido = 'Sessão do operador'      WHERE id = 120;
UPDATE public.operacao SET nome_reduzido = 'Adicionar Itens'         WHERE id = 121;
UPDATE public.operacao SET nome_reduzido = 'Sessão de Operador'      WHERE id = 122;
UPDATE public.operacao SET nome_reduzido = 'Identificar Cliente'     WHERE id = 123;
UPDATE public.operacao SET nome_reduzido = 'Funções Adicionais'      WHERE id = 125;
UPDATE public.operacao SET nome_reduzido = 'Reimprimir DANFe'        WHERE id = 126;
UPDATE public.operacao SET nome_reduzido = 'Liberar Cheque'          WHERE id = 127;
UPDATE public.operacao SET nome_reduzido = 'Devolução Mercadoria'    WHERE id = 128;
UPDATE public.operacao SET nome_reduzido = 'Chamar Fiscal'           WHERE id = 129;
UPDATE public.operacao SET nome_reduzido = 'Incluir Entrega'         WHERE id = 130;
UPDATE public.operacao SET nome_reduzido = 'Liberar Troco no Cheque' WHERE id = 131;
UPDATE public.operacao SET nome_reduzido = 'Chamar Fila'             WHERE id = 132;
UPDATE public.operacao SET nome_reduzido = 'Autorizar Cheque'        WHERE id = 133;
UPDATE public.operacao SET nome_reduzido = 'Adicionar Itens'         WHERE id = 134;
UPDATE public.operacao SET nome_reduzido = 'Menu NFC-e'              WHERE id = 135;
UPDATE public.operacao SET nome_reduzido = 'Cadastrar Senha'         WHERE id = 136;
UPDATE public.operacao SET nome_reduzido = 'Backup PDV'              WHERE id = 138;
UPDATE public.operacao SET nome_reduzido = 'Exportar NFC-e'          WHERE id = 139;
UPDATE public.operacao SET nome_reduzido = 'Verificar Conexão TK'    WHERE id = 140;
UPDATE public.operacao SET nome_reduzido = 'Reimprimir DANFe'        WHERE id = 141;
UPDATE public.operacao SET nome_reduzido = 'Reimprimir DANFe'    WHERE id = 142;
UPDATE public.operacao SET nome_reduzido = 'Gerar Arquivo DANFe' WHERE id = 143;
UPDATE public.operacao SET nome_reduzido = 'Cancelar Cupom'      WHERE id = 144;
UPDATE public.operacao SET nome_reduzido = 'Relatórios'          WHERE id = 145;
UPDATE public.operacao SET nome_reduzido = 'Consultar Itens'     WHERE id = 146;
UPDATE public.operacao SET nome_reduzido = 'Carteira Digital'    WHERE id = 147;
UPDATE public.operacao SET nome_reduzido = 'Liberação de Risco'  WHERE id = 999;
UPDATE public.operacao SET nome_reduzido = 'Sair do Sistema'     WHERE id = 1052;